[package]
name = "bampile"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.2"
flate2 = "1.0.27"
bam = "^0.1.4"
bio = "1"